version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  cadeo-mysql:
    image: mysql:latest
    hostname: cadeo-mysql
    domainname: cadeo-mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password42!
      MYSQL_DATABASE: cadeo
    volumes:
      - /datadisks/database:/var/lib/mysql

  cadeo-redis:
    image: redis:latest
    hostname: cadeo-redis
    domainname: cadeo-redis
    # restart: always
    ports:
     - "6379:6379"

  cadeo-api:
    image: cadeo-api
    hostname: cadeo-api
    domainname: cadeo-api
    depends_on:
     - cadeo-mysql
     - cadeo-redis
    # restart: always